# Generated by Django 5.2.6 on 2025-11-16 01:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('is_public', models.BooleanField(default=True, verbose_name='público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'colección multimedia',
                'verbose_name_plural': 'colecciones multimedia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de visualización')),
                ('duration_watched', models.PositiveIntegerField(default=0, help_text='Duración vista en segundos')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='mediacontent',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'contenido multimedia', 'verbose_name_plural': 'contenidos multimedia'},
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_media', to=settings.AUTH_USER_MODEL, verbose_name='aprobado por'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='attribution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='atribución'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='category',
            field=models.CharField(choices=[('cultural', 'Cultural Wayuu'), ('educational', 'Educativo'), ('language', 'Enseñanza de Idioma'), ('music', 'Música Tradicional'), ('crafts', 'Artesanías'), ('stories', 'Historias y Leyendas'), ('cooking', 'Gastronomía'), ('other', 'Otro')], default='cultural', max_length=20, verbose_name='categoría'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duración en segundos (para audio/video)', null=True),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='tamaño del archivo (bytes)'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='aprobado'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='destacado'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='público'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='license',
            field=models.CharField(choices=[('educational', 'Uso Educativo'), ('creative_commons', 'Creative Commons'), ('all_rights_reserved', 'Todos los derechos reservados')], default='educational', max_length=100, verbose_name='licencia'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Etiquetas para búsqueda'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media_thumbnails/%Y/%m/%d/', verbose_name='miniatura'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='file',
            field=models.FileField(upload_to='media_content/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'mp4', 'avi', 'mov', 'wmv', 'webm', 'mp3', 'wav', 'ogg', 'm4a', 'pdf', 'doc', 'docx', 'txt', 'ppt', 'pptx'])], verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='media_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Imagen'), ('document', 'Documento')], max_length=20, verbose_name='tipo de medio'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de subida'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='subido por'),
        ),
        migrations.AddIndex(
            model_name='mediacontent',
            index=models.Index(fields=['media_type', 'is_approved', 'is_public'], name='media_conte_media_t_1e96ec_idx'),
        ),
        migrations.AddIndex(
            model_name='mediacontent',
            index=models.Index(fields=['category', 'is_approved'], name='media_conte_categor_14afbe_idx'),
        ),
        migrations.AddIndex(
            model_name='mediacontent',
            index=models.Index(fields=['is_featured', 'uploaded_at'], name='media_conte_is_feat_2de580_idx'),
        ),
        migrations.AddIndex(
            model_name='mediacontent',
            index=models.Index(fields=['uploaded_by', 'uploaded_at'], name='media_conte_uploade_043811_idx'),
        ),
        migrations.AddField(
            model_name='mediacollection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_collections', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='mediacollection',
            name='media_files',
            field=models.ManyToManyField(blank=True, related_name='collections', to='media_content.mediacontent', verbose_name='archivos multimedia'),
        ),
        migrations.AddField(
            model_name='mediaview',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='media_content.mediacontent', verbose_name='contenido multimedia'),
        ),
        migrations.AddField(
            model_name='mediaview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_views', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddIndex(
            model_name='mediaview',
            index=models.Index(fields=['media', 'viewed_at'], name='media_conte_media_i_1531bc_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaview',
            index=models.Index(fields=['user', 'viewed_at'], name='media_conte_user_id_a760cd_idx'),
        ),
    ]
