/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TriggerEnum } from './triggerEnum';


export interface Badge { 
    readonly id: number;
    name: string;
    slug: string;
    description: string;
    icon?: string | null;
    trigger: TriggerEnum;
    /**
     * Valor numérico necesario para obtener la insignia (ej: 7 días de racha).
     */
    threshold?: number;
    xp_reward?: number;
}
export namespace Badge {
}


