/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `cultural` - Cultural Wayuu * `educational` - Educativo * `language` - Enseñanza de Idioma * `music` - Música Tradicional * `crafts` - Artesanías * `stories` - Historias y Leyendas * `cooking` - Gastronomía * `other` - Otro
 */
export const CategoryEnum = {
    Cultural: 'cultural',
    Educational: 'educational',
    Language: 'language',
    Music: 'music',
    Crafts: 'crafts',
    Stories: 'stories',
    Cooking: 'cooking',
    Other: 'other'
} as const;
export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];

