/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LevelRequiredEnum } from './levelRequiredEnum';
import { Difficulty911Enum } from './difficulty911Enum';


/**
 * Serializer principal de Course.  Usa los datos ya precargados por _optimized_course_queryset para evitar queries adicionales dentro del serializer (N+1).  Campos computados:   - enrolled_students_count → viene de la anotación enrollment_count   - completed_students_count → viene de la anotación completed_count   - quiz_count → viene de quiz_count_annotated   - is_enrolled → busca en user_enrollment (to_attr del Prefetch)   - user_progress → busca en user_enrollment (to_attr del Prefetch)
 */
export interface Course { 
    readonly id: number;
    title: string;
    description: string;
    level_required?: LevelRequiredEnum;
    is_active?: boolean;
    thumbnail?: string | null;
    /**
     * Duración estimada en horas
     */
    estimated_duration?: number;
    difficulty?: Difficulty911Enum;
    readonly created_by: number | null;
    readonly created_by_name: string;
    readonly created_at: string;
    readonly updated_at: string;
    readonly enrolled_students_count: number;
    readonly completed_students_count: number;
    /**
     * Lee user_enrollment (to_attr del Prefetch) si existe, así no lanza una query extra por cada curso en la lista.
     */
    readonly is_enrolled: boolean;
    /**
     * Igual que get_is_enrolled: prioriza el to_attr.
     */
    readonly user_progress: number;
    readonly quiz_count: number;
}
export namespace Course {
}


