/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Difficulty6abEnum } from './difficulty6abEnum';
import { QuestionRequest } from './questionRequest';


export interface CreateQuizRequest { 
    title: string;
    description?: string | null;
    course: number;
    difficulty?: Difficulty6abEnum;
    passing_score?: number;
    xp_reward?: number;
    /**
     * Tiempo límite en minutos
     */
    time_limit?: number;
    /**
     * Número máximo de intentos permitidos
     */
    max_attempts?: number;
    is_active?: boolean;
    questions?: Array<QuestionRequest>;
}
export namespace CreateQuizRequest {
}


