/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `easy` - Fácil * `medium` - Medio * `hard` - Difícil
 */
export const Difficulty6abEnum = {
    Easy: 'easy',
    Medium: 'medium',
    Hard: 'hard'
} as const;
export type Difficulty6abEnum = typeof Difficulty6abEnum[keyof typeof Difficulty6abEnum];

