/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `beginner` - Principiante * `intermediate` - Intermedio * `advanced` - Avanzado
 */
export const Difficulty911Enum = {
    Beginner: 'beginner',
    Intermediate: 'intermediate',
    Advanced: 'advanced'
} as const;
export type Difficulty911Enum = typeof Difficulty911Enum[keyof typeof Difficulty911Enum];

