/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Enrollment { 
    readonly id: number;
    course: number;
    readonly course_title: string;
    readonly course_level: number;
    progress?: number;
    course_completed?: boolean;
    completed_at?: string | null;
    readonly enrolled_at: string;
    readonly last_accessed: string;
}

