/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GlobalProgress { 
    readonly id: number;
    readonly user_name: string;
    readonly user_level: number;
    readonly user_xp: number;
    readonly total_courses_enrolled: number;
    readonly total_courses_completed: number;
    readonly total_quizzes_completed: number;
    readonly total_xp_earned: number;
    readonly average_progress: number;
    readonly completion_rate: string;
    readonly current_streak: number;
    readonly longest_streak: number;
    readonly updated_at: string;
}

