/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Leaderboard { 
    user_id: number;
    user_name: string;
    user_level: number;
    user_xp: number;
    total_courses_completed: number;
    total_quizzes_completed: number;
    current_streak: number;
    rank: number;
}

