/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `1` - Nivel 1 * `2` - Nivel 2 * `3` - Nivel 3 * `4` - Nivel 4 * `5` - Nivel 5 * `6` - Nivel 6 * `7` - Nivel 7 * `8` - Nivel 8 * `9` - Nivel 9 * `10` - Nivel 10
 */
export const LevelRequiredEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_9: 9,
    NUMBER_10: 10
} as const;
export type LevelRequiredEnum = typeof LevelRequiredEnum[keyof typeof LevelRequiredEnum];

