/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `educational` - Uso Educativo * `creative_commons` - Creative Commons * `all_rights_reserved` - Todos los derechos reservados
 */
export const LicenseEnum = {
    Educational: 'educational',
    CreativeCommons: 'creative_commons',
    AllRightsReserved: 'all_rights_reserved'
} as const;
export type LicenseEnum = typeof LicenseEnum[keyof typeof LicenseEnum];

