/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `0` - Vista * `1` - Aprendiendo * `2` - Familiar * `3` - Dominada
 */
export const MasteryLevelEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type MasteryLevelEnum = typeof MasteryLevelEnum[keyof typeof MasteryLevelEnum];

