/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryEnum } from './categoryEnum';
import { MediaTypeEnum } from './mediaTypeEnum';
import { LicenseEnum } from './licenseEnum';


export interface MediaContent { 
    readonly id: number;
    title: string;
    description?: string | null;
    media_type: MediaTypeEnum;
    category?: CategoryEnum;
    file: string;
    readonly file_size: number | null;
    readonly file_size_mb: string;
    /**
     * Duración en segundos (para audio/video)
     */
    duration?: number | null;
    readonly formatted_duration: string;
    thumbnail?: string | null;
    attribution?: string | null;
    license?: LicenseEnum;
    is_approved?: boolean;
    readonly approved_by: number | null;
    readonly approved_by_name: string | null;
    readonly approved_at: string | null;
    is_featured?: boolean;
    is_public?: boolean;
    readonly uploaded_by: number;
    readonly uploaded_by_name: string;
    readonly uploaded_by_email: string;
    readonly uploaded_at: string;
    readonly updated_at: string;
    /**
     * Etiquetas para búsqueda
     */
    tags?: any | null;
    readonly download_url: string;
    readonly preview_url: string;
    readonly view_count: string;
}
export namespace MediaContent {
}


