/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryEnum } from './categoryEnum';
import { MediaTypeEnum } from './mediaTypeEnum';
import { LicenseEnum } from './licenseEnum';


export interface MediaContentRequest { 
    title: string;
    description?: string | null;
    media_type: MediaTypeEnum;
    category?: CategoryEnum;
    file: Blob;
    /**
     * Duración en segundos (para audio/video)
     */
    duration?: number | null;
    thumbnail?: Blob | null;
    attribution?: string | null;
    license?: LicenseEnum;
    is_approved?: boolean;
    is_featured?: boolean;
    is_public?: boolean;
    /**
     * Etiquetas para búsqueda
     */
    tags?: any | null;
}
export namespace MediaContentRequest {
}


