/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `audio` - Audio * `video` - Video * `image` - Imagen * `document` - Documento
 */
export const MediaTypeEnum = {
    Audio: 'audio',
    Video: 'video',
    Image: 'image',
    Document: 'document'
} as const;
export type MediaTypeEnum = typeof MediaTypeEnum[keyof typeof MediaTypeEnum];

