/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaContent } from './mediaContent';


export interface MediaCollection { 
    readonly id: number;
    title: string;
    description?: string | null;
    readonly media_files: Array<MediaContent>;
    readonly media_count: string;
    readonly created_by: number;
    readonly created_by_name: string;
    is_public?: boolean;
    readonly created_at: string;
    readonly updated_at: string;
}

