/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryEnum } from './categoryEnum';
import { MediaTypeEnum } from './mediaTypeEnum';
import { LicenseEnum } from './licenseEnum';


export interface MediaContentCreate { 
    title: string;
    description?: string | null;
    media_type: MediaTypeEnum;
    category?: CategoryEnum;
    file: string;
    thumbnail?: string | null;
    attribution?: string | null;
    license?: LicenseEnum;
    tags?: string;
}
export namespace MediaContentCreate {
}


