/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeEnum } from './typeEnum';


export interface Notification { 
    readonly id: number;
    readonly title: string;
    readonly message: string;
    readonly type: TypeEnum;
    readonly is_read: boolean;
    created_at: string;
    readonly related_course_id: number | null;
    readonly related_quiz_id: number | null;
}
export namespace Notification {
}


