/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VocabularyCategory } from './vocabularyCategory';


export interface PaginatedVocabularyCategoryList { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<VocabularyCategory>;
}

