/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuizAttempt } from './quizAttempt';


export interface PaginatedQuizAttemptList { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<QuizAttempt>;
}

