/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MediaCollection } from './mediaCollection';


export interface PaginatedMediaCollectionList { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<MediaCollection>;
}

