/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Course } from './course';


export interface PaginatedCourseList { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Course>;
}

