/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VocabularyEntry } from './vocabularyEntry';


export interface PaginatedVocabularyEntryList { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<VocabularyEntry>;
}

