/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedUserRequest { 
    email?: string;
    first_name?: string;
    last_name?: string;
    bio?: string | null;
}

