/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LevelRequiredEnum } from './levelRequiredEnum';
import { Difficulty911Enum } from './difficulty911Enum';


export interface PatchedCreateCourseRequest { 
    title?: string;
    description?: string;
    level_required?: LevelRequiredEnum;
    thumbnail?: Blob | null;
    /**
     * Duración estimada en horas
     */
    estimated_duration?: number;
    difficulty?: Difficulty911Enum;
}
export namespace PatchedCreateCourseRequest {
}


