/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleEnum } from './roleEnum';


export interface PatchedUserRoleUpdateRequest { 
    role?: RoleEnum;
}
export namespace PatchedUserRoleUpdateRequest {
}


