/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryEnum } from './categoryEnum';
import { LicenseEnum } from './licenseEnum';


export interface PatchedMediaContentUpdateRequest { 
    title?: string;
    description?: string | null;
    category?: CategoryEnum;
    thumbnail?: Blob | null;
    attribution?: string | null;
    license?: LicenseEnum;
    is_public?: boolean;
    /**
     * Etiquetas para búsqueda
     */
    tags?: any | null;
}
export namespace PatchedMediaContentUpdateRequest {
}


