/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Profile { 
    readonly avatar: string | null;
    readonly telefono: string | null;
    readonly gustos: any | null;
    readonly fecha_nacimiento: string | null;
    readonly localidad: string | null;
}

