/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Course } from './course';


export interface Progress { 
    readonly id: number;
    readonly course: Course;
    readonly course_title: string;
    readonly course_difficulty: string;
    readonly completed_quizzes: number;
    readonly total_quizzes: number;
    readonly remaining_quizzes: string;
    readonly percentage: number;
    readonly xp_earned: number;
    readonly course_completed: boolean;
    readonly completed_at: string | null;
    /**
     * Días consecutivos estudiando este curso
     */
    readonly streak_days: number;
    readonly estimated_completion_time: string;
    readonly updated_at: string;
}

