/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestionOption } from './questionOption';
import { QuestionTypeEnum } from './questionTypeEnum';


/**
 * Serializer de Question. Valida que el JSONField `options` tenga exactamente 1 opción correcta cuando el tipo es \'multiple_choice\'.
 */
export interface Question { 
    readonly id: number;
    text: string;
    question_type?: QuestionTypeEnum;
    options?: Array<QuestionOption>;
    /**
     * Orden de la pregunta en el quiz
     */
    order?: number;
    /**
     * Explicación de la respuesta correcta
     */
    explanation?: string | null;
}
export namespace Question {
}


