/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `multiple_choice` - Selección múltiple * `true_false` - Verdadero/Falso * `short_answer` - Respuesta corta
 */
export const QuestionTypeEnum = {
    MultipleChoice: 'multiple_choice',
    TrueFalse: 'true_false',
    ShortAnswer: 'short_answer'
} as const;
export type QuestionTypeEnum = typeof QuestionTypeEnum[keyof typeof QuestionTypeEnum];

