/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sub-serializer que documenta y valida la estructura del JSONField `options` del modelo Question.  Ventaja frente a una tabla intermedia (QuestionOption):   - Sin JOINs adicionales al consultar preguntas   - Flexible: añadir campos (imagen, audio) sin migración   - Consultable con operadores JSON nativos de PostgreSQL:       Question.objects.filter(options__contains=[{\"is_correct\": True}])  Estructura esperada en `options`: [   {\"id\": \"a\", \"text\": \"Taya\", \"is_correct\": true},   {\"id\": \"b\", \"text\": \"Wayuu\", \"is_correct\": false},   {\"id\": \"c\", \"text\": \"Ouuya\", \"is_correct\": false} ]
 */
export interface QuestionOptionRequest { 
    /**
     * Identificador de la opción (ej: \'a\', \'b\', \'c\').
     */
    id: string;
    /**
     * Texto de la opción de respuesta.
     */
    text: string;
    /**
     * True si esta es la respuesta correcta.
     */
    is_correct: boolean;
    /**
     * URL opcional a un audio de pronunciación para la opción.
     */
    audio_url?: string;
}

