/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Difficulty6abEnum } from './difficulty6abEnum';
import { Question } from './question';


export interface Quiz { 
    readonly id: number;
    title: string;
    description?: string | null;
    course: number;
    readonly course_title: string;
    difficulty?: Difficulty6abEnum;
    passing_score?: number;
    xp_reward?: number;
    /**
     * Tiempo límite en minutos
     */
    time_limit?: number;
    is_active?: boolean;
    /**
     * Número máximo de intentos permitidos
     */
    max_attempts?: number;
    readonly questions: Array<Question>;
    readonly question_count: string;
    readonly average_score: string;
    readonly completion_rate: string;
    readonly user_attempts: number;
    readonly can_attempt: boolean;
    readonly best_score: number;
    readonly created_by: number | null;
    readonly created_at: string;
}
export namespace Quiz {
}


