/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuizStatistics { 
    total_quizzes: number;
    total_attempts: number;
    average_score: number;
    pass_rate: number;
    popular_quizzes: Array<any>;
}

