/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface QuizAttempt { 
    readonly id: number;
    quiz: number;
    readonly quiz_title: string;
    readonly course_title: string;
    score?: number;
    readonly passed: boolean;
    /**
     * Tiempo tomado en segundos
     */
    time_taken?: number;
    /**
     * Respuestas del usuario en formato JSON
     */
    answers?: any | null;
    readonly attempt_number: string;
    readonly can_retake: string;
    readonly completed_at: string;
}

