/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `admin` - Administrador * `moderator` - Moderador * `user` - Usuario
 */
export const RoleEnum = {
    Admin: 'admin',
    Moderator: 'moderator',
    User: 'user'
} as const;
export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];

