/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Streak { 
    current_streak?: number;
    longest_streak?: number;
    last_activity_date?: string | null;
    /**
     * Permiten al usuario conservar su racha un día sin actividad.
     */
    freeze_tokens?: number;
}

