/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * `answers` es un JSONField: mapa de question_id → respuesta elegida.  Ejemplo: {   \"quiz_id\": 3,   \"time_taken\": 120,   \"answers\": {     \"10\": \"a\",     \"11\": \"true\",     \"12\": \"taya\"   } }
 */
export interface SubmitQuizRequest { 
    quiz_id: number;
    /**
     * Mapa {\"<question_id>\": \"<opción_elegida>\"}
     */
    answers: any | null;
    time_taken: number;
}

