/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `streak` - Racha de días * `lessons` - Lecciones completadas * `quiz_perfect` - Quiz perfecto * `vocab` - Vocabulario dominado * `first_login` - Primer inicio de sesión * `course` - Curso completado
 */
export const TriggerEnum = {
    Streak: 'streak',
    Lessons: 'lessons',
    QuizPerfect: 'quiz_perfect',
    Vocab: 'vocab',
    FirstLogin: 'first_login',
    Course: 'course'
} as const;
export type TriggerEnum = typeof TriggerEnum[keyof typeof TriggerEnum];

