/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `new_course` - Nuevo curso disponible * `new_quiz` - Nuevo quiz disponible * `progress_update` - Progreso actualizado * `level_up` - Nivel aumentado * `user_report` - Usuario reportó un problema * `course_completed` - Usuario completó curso * `new_moderator` - Nuevo moderador registrado * `system_error` - Error crítico del sistema * `study_streak` - Racha de estudio * `reward_unlocked` - Recompensa desbloqueada * `system` - Sistema
 */
export const TypeEnum = {
    NewCourse: 'new_course',
    NewQuiz: 'new_quiz',
    ProgressUpdate: 'progress_update',
    LevelUp: 'level_up',
    UserReport: 'user_report',
    CourseCompleted: 'course_completed',
    NewModerator: 'new_moderator',
    SystemError: 'system_error',
    StudyStreak: 'study_streak',
    RewardUnlocked: 'reward_unlocked',
    System: 'system'
} as const;
export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];

