/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sub-serializer documentativo para los ejemplos JSON.
 */
export interface UsageExample { 
    spanish: string;
    wayuunaiki: string;
    context?: string;
}

