/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Badge } from './badge';


export interface UserBadge { 
    readonly id: number;
    readonly badge: Badge;
    readonly earned_at: string;
}

