/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MasteryLevelEnum } from './masteryLevelEnum';
import { VocabularyEntry } from './vocabularyEntry';


export interface UserVocabularyProgress { 
    readonly id: number;
    readonly entry: VocabularyEntry;
    mastery_level?: MasteryLevelEnum;
    readonly review_count: number;
    next_review_at?: string | null;
    readonly last_seen_at: string;
}
export namespace UserVocabularyProgress {
}


