/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleEnum } from './roleEnum';
import { Profile } from './profile';


export interface User { 
    readonly id: number;
    email: string;
    readonly role: RoleEnum;
    readonly level: number;
    readonly xp: number;
    first_name?: string;
    last_name?: string;
    bio?: string | null;
    readonly full_name: string;
    readonly date_joined: string;
    readonly last_login: string | null;
    readonly profile: Profile;
}
export namespace User {
}


