/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsageExample } from './usageExample';
import { VocabularyCategory } from './vocabularyCategory';
import { WordTypeEnum } from './wordTypeEnum';
import { Difficulty911Enum } from './difficulty911Enum';


export interface VocabularyEntry { 
    readonly id: number;
    spanish_term: string;
    wayuunaiki_translation: string;
    /**
     * Representación fonética aproximada para hispanohablantes.
     */
    phonetic_transcription?: string;
    readonly category: VocabularyCategory;
    word_type?: WordTypeEnum;
    difficulty?: Difficulty911Enum;
    /**
     * Archivo de audio .mp3 o .ogg con la pronunciación nativa.
     */
    audio_pronunciation?: string | null;
    image?: string | null;
    usage_examples?: Array<UsageExample>;
    /**
     * Aparece en la sección \'Palabra del día\'.
     */
    is_featured?: boolean;
    is_active?: boolean;
    readonly created_at: string;
}
export namespace VocabularyEntry {
}


