/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VocabularyCategory { 
    readonly id: number;
    name: string;
    slug: string;
    description?: string;
    icon?: string;
    order?: number;
}

