/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WordTypeEnum } from './wordTypeEnum';
import { Difficulty911Enum } from './difficulty911Enum';
import { UsageExampleRequest } from './usageExampleRequest';


export interface VocabularyEntryRequest { 
    spanish_term: string;
    wayuunaiki_translation: string;
    /**
     * Representación fonética aproximada para hispanohablantes.
     */
    phonetic_transcription?: string;
    category_id?: number;
    word_type?: WordTypeEnum;
    difficulty?: Difficulty911Enum;
    /**
     * Archivo de audio .mp3 o .ogg con la pronunciación nativa.
     */
    audio_pronunciation?: Blob | null;
    image?: Blob | null;
    usage_examples?: Array<UsageExampleRequest>;
    /**
     * Aparece en la sección \'Palabra del día\'.
     */
    is_featured?: boolean;
    is_active?: boolean;
}
export namespace VocabularyEntryRequest {
}


