/**
 * Yonna Akademia API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `noun` - Sustantivo * `verb` - Verbo * `adjective` - Adjetivo * `adverb` - Adverbio * `phrase` - Frase * `greeting` - Saludo * `other` - Otro
 */
export const WordTypeEnum = {
    Noun: 'noun',
    Verb: 'verb',
    Adjective: 'adjective',
    Adverb: 'adverb',
    Phrase: 'phrase',
    Greeting: 'greeting',
    Other: 'other'
} as const;
export type WordTypeEnum = typeof WordTypeEnum[keyof typeof WordTypeEnum];

