# Generated by Django 5.2.6 on 2025-11-16 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_course_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_quiz_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_course', 'Nuevo curso disponible'), ('new_quiz', 'Nuevo quiz disponible'), ('progress_update', 'Progreso actualizado'), ('level_up', 'Nivel aumentado'), ('user_report', 'Usuario reportó un problema'), ('course_completed', 'Usuario completó curso'), ('new_moderator', 'Nuevo moderador registrado'), ('system_error', 'Error crítico del sistema'), ('study_streak', 'Racha de estudio'), ('reward_unlocked', 'Recompensa desbloqueada'), ('system', 'Sistema')], default='system', max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_8a7c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'created_at'], name='notificatio_type_8e213d_idx'),
        ),
    ]
