# Generated by Django 5.2.6 on 2026-04-30 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Categoría')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícono (emoji o clave de ícono)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Categoría de vocabulario',
                'verbose_name_plural': 'Categorías de vocabulario',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish_term', models.CharField(db_index=True, max_length=200, verbose_name='Término en español')),
                ('wayuunaiki_translation', models.CharField(db_index=True, max_length=200, verbose_name='Traducción al Wayuunaiki')),
                ('phonetic_transcription', models.CharField(blank=True, help_text='Representación fonética aproximada para hispanohablantes.', max_length=200, verbose_name='Transcripción fonética')),
                ('word_type', models.CharField(choices=[('noun', 'Sustantivo'), ('verb', 'Verbo'), ('adjective', 'Adjetivo'), ('adverb', 'Adverbio'), ('phrase', 'Frase'), ('greeting', 'Saludo'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de palabra')),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20, verbose_name='Nivel de dificultad')),
                ('audio_pronunciation', models.FileField(blank=True, help_text='Archivo de audio .mp3 o .ogg con la pronunciación nativa.', null=True, upload_to='vocabulary/audio/%Y/%m/', verbose_name='Audio de pronunciación')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vocabulary/images/%Y/%m/', verbose_name='Imagen ilustrativa')),
                ('usage_examples', models.JSONField(blank=True, default=list, help_text='Lista de objetos JSON con la estructura: [{"spanish": "...", "wayuunaiki": "...", "context": "..."}]', verbose_name='Ejemplos de uso')),
                ('is_featured', models.BooleanField(default=False, help_text="Aparece en la sección 'Palabra del día'.", verbose_name='Destacada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='vocabulary.vocabularycategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Entrada de vocabulario',
                'verbose_name_plural': 'Entradas de vocabulario',
                'ordering': ['spanish_term'],
            },
        ),
        migrations.CreateModel(
            name='UserVocabularyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.SmallIntegerField(choices=[(0, 'Vista'), (1, 'Aprendiendo'), (2, 'Familiar'), (3, 'Dominada')], default=0, verbose_name='Nivel de dominio')),
                ('review_count', models.PositiveSmallIntegerField(default=0, verbose_name='Veces practicada')),
                ('next_review_at', models.DateTimeField(blank=True, null=True, verbose_name='Próxima revisión (SRS)')),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_progress', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='vocabulary.vocabularyentry', verbose_name='Entrada')),
            ],
            options={
                'verbose_name': 'Progreso de vocabulario',
                'verbose_name_plural': 'Progresos de vocabulario',
            },
        ),
        migrations.AddIndex(
            model_name='vocabularyentry',
            index=models.Index(fields=['category', 'difficulty'], name='vocabulary__categor_7e9d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyentry',
            index=models.Index(fields=['word_type'], name='vocabulary__word_ty_cf3130_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyentry',
            index=models.Index(fields=['is_featured', 'is_active'], name='vocabulary__is_feat_1a8e6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='uservocabularyprogress',
            unique_together={('user', 'entry')},
        ),
    ]
