# Generated by Django 5.2.6 on 2025-11-16 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_difficulty_course_estimated_duration_and_more'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_courses_enrolled', models.PositiveIntegerField(default=0)),
                ('total_courses_completed', models.PositiveIntegerField(default=0)),
                ('total_quizzes_completed', models.PositiveIntegerField(default=0)),
                ('total_xp_earned', models.PositiveIntegerField(default=0)),
                ('average_progress', models.FloatField(default=0.0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Global Progress',
            },
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name_plural': 'Progress'},
        ),
        migrations.AddField(
            model_name='progress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='course_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='last_study_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='streak_days',
            field=models.PositiveIntegerField(default=0, help_text='Días consecutivos estudiando este curso'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['user', 'course_completed'], name='progress_pr_user_id_679c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['course', 'percentage'], name='progress_pr_course__5f3ced_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['updated_at'], name='progress_pr_updated_ecba19_idx'),
        ),
        migrations.AddField(
            model_name='globalprogress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
