# Generated by Django 5.2.6 on 2025-11-16 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_difficulty_course_estimated_duration_and_more'),
        ('quizzes', '0002_alter_question_options_alter_quiz_options_and_more'),
        ('stats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('new_users_today', models.PositiveIntegerField(default=0)),
                ('active_users_today', models.PositiveIntegerField(default=0)),
                ('total_quizzes_taken', models.PositiveIntegerField(default=0)),
                ('total_xp_gained', models.PositiveIntegerField(default=0)),
                ('total_courses_started', models.PositiveIntegerField(default=0)),
                ('total_courses_completed', models.PositiveIntegerField(default=0)),
                ('average_session_time', models.PositiveIntegerField(default=0)),
                ('average_user_level', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quizzes_attempted', models.PositiveIntegerField(default=0)),
                ('total_quizzes_passed', models.PositiveIntegerField(default=0)),
                ('average_quiz_score', models.FloatField(default=0.0)),
                ('total_courses_started', models.PositiveIntegerField(default=0)),
                ('total_courses_completed', models.PositiveIntegerField(default=0)),
                ('total_study_time_minutes', models.PositiveIntegerField(default=0)),
                ('current_streak_days', models.PositiveIntegerField(default=0)),
                ('longest_streak_days', models.PositiveIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('total_xp_earned', models.PositiveIntegerField(default=0)),
                ('days_active', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='xphistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'XP History'},
        ),
        migrations.AddField(
            model_name='xphistory',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xphistory',
            name='related_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='courses.course'),
        ),
        migrations.AddField(
            model_name='xphistory',
            name='related_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='quizzes.quiz'),
        ),
        migrations.AlterField(
            model_name='xphistory',
            name='source',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('course_completion', 'Completación de Curso'), ('daily_streak', 'Racha Diaria'), ('achievement', 'Logro'), ('system_bonus', 'Bonus del Sistema'), ('level_up', 'Subida de Nivel'), ('correction', 'Corrección')], default='quiz', max_length=20),
        ),
        migrations.AddIndex(
            model_name='xphistory',
            index=models.Index(fields=['user', 'created_at'], name='stats_xphis_user_id_251da2_idx'),
        ),
        migrations.AddIndex(
            model_name='xphistory',
            index=models.Index(fields=['source', 'created_at'], name='stats_xphis_source_7dfffd_idx'),
        ),
        migrations.AddIndex(
            model_name='xphistory',
            index=models.Index(fields=['created_at'], name='stats_xphis_created_76fc9e_idx'),
        ),
        migrations.AddIndex(
            model_name='platformstatistic',
            index=models.Index(fields=['date'], name='stats_platf_date_cb2bc6_idx'),
        ),
        migrations.AddField(
            model_name='userstatistic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userstatistic',
            index=models.Index(fields=['user', 'updated_at'], name='stats_users_user_id_30f27b_idx'),
        ),
    ]
