# Generated by Django 5.2.6 on 2025-11-16 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_difficulty_course_estimated_duration_and_more'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['quiz', 'order']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['course', 'title'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explicación de la respuesta correcta', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de la pregunta en el quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Selección múltiple'), ('true_false', 'Verdadero/Falso'), ('short_answer', 'Respuesta corta')], default='multiple_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, help_text='Número máximo de intentos permitidos'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(default=10, help_text='Tiempo límite en minutos'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(default=dict, help_text='Respuestas del usuario en formato JSON'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo tomado en segundos'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(help_text='Respuesta correcta', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(default=list, help_text='Lista de opciones para preguntas de selección múltiple'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('user', 'quiz')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='quizzes_que_quiz_id_904735_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['course', 'is_active'], name='quizzes_qui_course__0ca1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['difficulty', 'is_active'], name='quizzes_qui_difficu_ea5416_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz'], name='quizzes_qui_user_id_68ef05_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['completed_at'], name='quizzes_qui_complet_88ab64_idx'),
        ),
    ]
