export * from './autenticacin.service';
import { AutenticacinService } from './autenticacin.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './cursos.service';
import { CursosService } from './cursos.service';
export * from './estadsticas.service';
import { EstadsticasService } from './estadsticas.service';
export * from './gamificacin.service';
import { GamificacinService } from './gamificacin.service';
export * from './media.service';
import { MediaService } from './media.service';
export * from './notificaciones.service';
import { NotificacionesService } from './notificaciones.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './progreso.service';
import { ProgresoService } from './progreso.service';
export * from './progress.service';
import { ProgressService } from './progress.service';
export * from './quizzes.service';
import { QuizzesService } from './quizzes.service';
export * from './token.service';
import { TokenService } from './token.service';
export * from './vocabulario.service';
import { VocabularioService } from './vocabulario.service';
export const APIS = [AutenticacinService, AuthService, CursosService, EstadsticasService, GamificacinService, MediaService, NotificacionesService, NotificationsService, ProgresoService, ProgressService, QuizzesService, TokenService, VocabularioService];
