# Generated by Django 5.2.6 on 2026-04-30 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/icons/', verbose_name='Ícono')),
                ('trigger', models.CharField(choices=[('streak', 'Racha de días'), ('lessons', 'Lecciones completadas'), ('quiz_perfect', 'Quiz perfecto'), ('vocab', 'Vocabulario dominado'), ('first_login', 'Primer inicio de sesión'), ('course', 'Curso completado')], max_length=30, verbose_name='Condición de disparo')),
                ('threshold', models.PositiveIntegerField(default=1, help_text='Valor numérico necesario para obtener la insignia (ej: 7 días de racha).', verbose_name='Umbral')),
                ('xp_reward', models.PositiveIntegerField(default=0, verbose_name='XP otorgada al obtener la insignia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Insignia',
                'verbose_name_plural': 'Insignias',
                'ordering': ['trigger', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Racha actual (días)')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Racha más larga (días)')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Última actividad')),
                ('freeze_tokens', models.PositiveSmallIntegerField(default=0, help_text='Permiten al usuario conservar su racha un día sin actividad.', verbose_name='Tokens de congelación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Racha',
                'verbose_name_plural': 'Rachas',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Obtenida el')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='gamification.badge', verbose_name='Insignia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Insignia de usuario',
                'verbose_name_plural': 'Insignias de usuarios',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positivo para ganancias, negativo para penalizaciones.', verbose_name='Cantidad de XP')),
                ('reason', models.CharField(choices=[('lesson_complete', 'Lección completada'), ('quiz_passed', 'Quiz aprobado'), ('quiz_perfect', 'Quiz perfecto (100%)'), ('streak_bonus', 'Bono de racha'), ('badge_earned', 'Insignia obtenida'), ('vocab_mastered', 'Palabra dominada'), ('admin', 'Ajuste manual')], max_length=30, verbose_name='Motivo')),
                ('reference_id', models.PositiveBigIntegerField(blank=True, help_text='Ej: ID de la lección completada.', null=True, verbose_name='ID del objeto relacionado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Transacción de XP',
                'verbose_name_plural': 'Transacciones de XP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='gamificatio_user_id_4000e4_idx')],
            },
        ),
    ]
